sakanytaurus/sakanyapp/urls.py
from django.urls import path
from . import views

app_name = 'sakanyapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('findpub/', views.findpub, name='findpub'),
    path('newcrawl/', views.newcrawl, name='newcrawl'),
    path('profile/', views.profile, name='profile'),
    path('delete/<int:route_id>/', views.delete_route, name='delete'),
    path('routes/', views.routes, name='routes'),
    path('compass/', views.compass, name='compass')
]

sakanytaurus/sakanytaurus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sakanyapp.urls'))
]

sakanytaurus/sakanyapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime

# Create your models here.
class UserRoute(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length = 20)
    creation_dtg = models.DateTimeField(
        default = datetime.now
    )
    start_time = models.DateTimeField(
        blank = True,
        null = True
    )
    end_time = models.DateTimeField(
        blank = True,
        null = True
    )

    def start_dt (self):
        return self.start_time.strftime("%d %b %Y %H:%M") if self.start_time else ''

    def end_dt (self):
        return self.end_time.strftime("%d %b %Y %H:%M") if self.end_time else ''

    def __str__(self):
        return 'User: ' + str(self.creator) + ' | Route Name: ' + self.name + ' | Start: ' + self.start_dt() + ' | End: ' + self.end_dt()

class RouteStep(models.Model):
    route = models.ForeignKey(UserRoute, on_delete=models.CASCADE, related_name='steps')
    order_num = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)])
    loc_name = models.CharField(max_length = 30)
    loc_rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    loc_address = models.TextField()
    loc_lat = models.FloatField()
    loc_lon = models.FloatField()
    open_time = models.DateTimeField(
        blank = True,
        null = True
    )
    close_time = models.DateTimeField(
        blank = True,
        null = True
    )
    arr_time = models.DateTimeField(
        blank = True,
        null = True
    )
    visited = models.BooleanField(default=False)
    distance = models.FloatField()
    newdistance = models.FloatField()
    unit = models.CharField(max_length = 20)
    stars = models.PositiveSmallIntegerField()
    halfstar = models.FloatField()
    review_count = models.PositiveSmallIntegerField()

    def __str__(self):
        return ' Route: ' + self.route.name + ' | Step: ' + str(self.order_num) + ' | Arrival Time: ' + str(self.arr_time) + ' | Visited: ' + str(self.visited)

sakanytaurus/sakanyapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from . import secrets
from .models import UserRoute, RouteStep

import requests
import json

# Create your views here.
#
# def register(request):
#     return render(request, 'users/register.html')
#
# def register_user(request):
#     username = request.POST['username']
#     email = request.POST['email']
#     password = request.POST['password']
#     user = User.objects.create_user(username, email, password)
#     login(request, user)
#     return HttpResponseRedirect(reverse(''))

# Renders login page
def login_page(request):
    message = request.GET.get('message', '')
    next = request.GET.get('next', '')
    context = {
        'next': next, #redirects to previously-viewed pages
        'message': message
    }
    return render(request, 'sakanyapp/login.html', context)

# User authentication
def user_login (request):
    next = request.POST['next']
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next != '':
            return HttpResponseRedirect(next)
        return HttpResponseRedirect(reverse('sakanyapp:index'))
    if next == '':
        return HttpResponseRedirect(reverse('sakanyapp:login') + '?message=failure')
    return HttpResponseRedirect(reverse('sakanyapp:login') + '?message=failure&next='+next)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('sakanyapp:login'))

@login_required
def index(request):
    context = {
        'mapapi': secrets.mapapi #calls map api for use with Google Maps
    }
    return render(request, 'sakanyapp/index.html', context)

# Conduct API pulls of Google Maps and Yelp APIs
@login_required
def findpub(request):
    save_json = json.loads(request.body)
    address = save_json['address']
    #access api using address string and api key
    map_url = f'https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={secrets.mapapi}'
    map_response = requests.get(map_url)
    #pull coordinates
    geocoords = json.loads(map_response.text)['results'][0]['geometry']['location']

    yelpurl = f"https://api.yelp.com/v3/businesses/search?latitude={geocoords['lat']}&longitude={geocoords['lng']}&sort_by=distance&categories=breweries,brewpubs,beerbar,divebars,irish_pubs,pubs,beergarden,beergardens,barcrawl,beerhall"

    yelpheaders = {'Authorization': 'Bearer %s' % secrets.yelpapi}
    yelpresponse = requests.get(yelpurl, headers=yelpheaders)
    yelpdata = json.loads(yelpresponse.text)['businesses']
    #
    origin = (geocoords['lat'],geocoords['lng'])

    return JsonResponse({'pubresults':yelpdata,'origin':origin})

# Saves user-create pub crawl route
@login_required
def newcrawl(request):
    json_data = json.loads(request.body)
    pub_route = json_data['pub_route']
    route = json_data['crawlname']
    print(json_data['pub_route'])
    print(json_data['crawlname'])

    newcrawl = UserRoute(creator=request.user, name=route)
    newcrawl.save()

    order_num = 0
    for pub in pub_route:
        order_num += 1
        loc_name = pub['name']
        loc_rating = pub['rating']
        print(pub['location']['display_address'])
        loc_address = ', '.join(pub['location']['display_address'])
        loc_lat = pub['coordinates']['latitude']
        loc_lon = pub['coordinates']['longitude']
        distance = pub['distance']
        newdistance = float(pub['newdistance'])
        unit = pub['unit']
        stars = pub['stars']
        halfstar = pub['halfstar']
        review_count = pub['review_count']

        create_crawl = RouteStep(route=newcrawl, order_num=order_num, loc_name=loc_name, loc_rating=loc_rating, loc_address=loc_address, loc_lat=loc_lat, loc_lon=loc_lon, distance=distance, newdistance=newdistance, unit=unit, stars=stars, halfstar=halfstar, review_count=review_count)
        create_crawl.save()

    return HttpResponseRedirect(reverse('sakanyapp:profile'))

@login_required
def profile(request):
    return render(request, 'sakanyapp/profile.html')

#pulls route information for profile pages
@login_required
def routes(request):
    routes = UserRoute.objects.all().filter(creator=request.user)
    data = []
    for route in routes:
        route_id = route.id
        start_dt = ''
        start_time = ''
        end_dt = ''
        end_time = ''
        creation_dtg = str(route.creation_dtg)
        create_dt = route.creation_dtg.strftime('%Y/%m/%d')
        create_time = route.creation_dtg.strftime('%H:%M')

        if route.start_time:
            start_dt = route.start_time.strftime('%m/%d/%Y')
            start_time = route.start_time.strftime('%H:%M')
        if route.end_time:
            end_dt = route.end_time.strftime('%m/%d/%Y')
            end_time = route.end_time.strftime('%H:%M:%S')

        steps = RouteStep.objects.all().filter(route=route)
        routesteps = []

        for step in steps:
            open_dt = ''
            open_time = ''
            close_dt = ''
            close_time = ''
            arr_date = ''
            arr_time = ''
            if step.open_time:
                open_dt = step.open_time.strftime('%m/%d/%Y')
                open_time = step.open_time.strftime('%H:%M')
            if step.close_time:
                close_dt = step.close_time.strftime('%m/%d/%Y')
                close_time = step.close_time.strftime('%H:%M')
            if step.arr_time:
                arr_date = step.arr_time.strftime('%m/%d/%Y')
                arr_time = step.arr_time.strftime('%H:%M')
            routesteps.append({
                'order_num': step.order_num,
                'loc_name': step.loc_name,
                'loc_rating': step.loc_rating,
                'loc_address': step.loc_address,
                'loc_lat': step.loc_lat,
                'loc_lon': step.loc_lon,
                'distance': step.distance,
                'newdistance': step.newdistance,
                'unit': step.unit,
                'stars': step.stars,
                'halfstar': step.halfstar,
                'review_count': step.review_count,
                'open_dt': open_dt,
                'open_time': open_time,
                'close_dt': close_dt,
                'close_time': close_time,
                'arr_date': arr_date,
                'arr_time': arr_time,
                'visited': str(step.visited)
            })
        data.append({
            'id': route_id,
            'name': route.name,
            'creation_dtg': creation_dtg,
            'create_dt': create_dt,
            'create_time': create_time,
            'start_dt': start_dt,
            'start_time': start_time,
            'end_dt': end_dt,
            'end_time': end_time,
            'steps': routesteps
        })
        sortdata = data
        # Sorts pub routes, newest first
        data = sorted(sortdata, key=lambda i: i['creation_dtg'], reverse=True)

    # terminal testing
    for dat in data:
        print("name: " + dat['name'])
        print("start_dt / start_time: " + dat['start_dt'] + " / " + dat['start_time'])
        print("end_dt / end_time: " + dat['end_dt'] + " / " + dat['end_time'])
        for step in dat["steps"]:
            print(step)
    return JsonResponse({'routes': data})

# delete routes from profile page
@login_required
def delete_route(request, route_id):
    route = UserRoute.objects.get(id=route_id)
    route.delete()
    return HttpResponseRedirect(reverse('sakanyapp:profile'))

@login_required
def compass(request):
    # print(request.body)
    # json_data = json.loads(request.body)
    publat = request.GET["publat"]
    publon = request.GET["publon"]
    context = {
        'publat': publat,
        'publon': publon,
    }
    return render(request, 'sakanyapp/compass.html', context)

sakanytaurus/sakanyapp/templates/sakanyapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- import Vue framework -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script type="text/javascript" src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!-- import Pure CSS framework -->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" SameSite=None>
    <link rel="stylesheet" href="/static/sakanyapp/stylesheet.css">
    {% load static %}
    <title></title>
  </head>
  <body>
    <div id="app">
      <!-- creates title header with profile and logout buttons -->
      <div class="header">
        <div class="home-menu pure-menu-horizontal pure-menu-fixed">
            <div class="">
              <a class="pure-menu-heading" href="/"><img src="{% static "sakanyapp/logo2.png" %}" alt="logo"></a>
              <div class="pure-menu-heading">A Pub Crawler</div>
            </div>
            <div class="pure-menu-buttons">
                <a class="pure-button" href="/profile">PROFILE</a>
                <a class="pure-button" href="/logout">LOGOUT</a>
            </div>
        </div>
      </div>
      <div class="main">
        <!-- Starting address form -->
        <div class="pure-form pure-flex-row">
          <input type="text" v-model="address" placeholder="Input a starting address" v-on:keypress.enter="submitAddress">
          <!-- Initiate axios call -->
          <button type="submit" class="pure-button" v-on:click="submitAddress">Submit</button>
        </div>
        <!-- Display array of nearby pubs after submission of starting address -->
        <div class="pure-g" v-if="submitted">
          <div class="pure-u-1-2">
            <div class="pure-menu custom-restricted-width">
              <h3>Nearby pubs:</h3>
              <h6>click to add</h6>
              <ul class="pure-menu-list">
                <!-- Clicking on pub card moves it to the array of selected locations -->
                <li @click="pubSelected(pub, i)" v-for="(pub, i) in pubresults" class="pure-menu-item pure-flex-container pure-flex-column">
                  <div v-html="pub.name"></div>
                  <div v-html="pub.location.address1"></div>
                  <div>
                    <span v-html="pub.location.city"></span>, <span v-html="pub.location.state"></span> <span v-html="pub.location.zip_code"></span>
                  </div>
                  <div v-bind:style="{ fontSize: .7 + 'em' }" class="pure-flex-row">
                    <!-- Newdistance and unit calculated after axios call -->
                    <div>[[pub.newdistance]] [[pub.unit]]</div>
                    <div>
                      <!-- iterates over the number of stars in the rating, displays a half star if pub.halfstar is a nonzero value, and shows the number of reviews -->
                      <i class="fa fa-star" v-for="i in pub.stars"></i><i class="fa fa-star-half" v-if="pub.halfstar > 0"></i><span> ([[pub.review_count]])</span>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <!-- Displays once a location is selected and moved from the list of nearby pubs -->
          <div class="pure-u-1-2" v-if="selectedpubs[0]">
            <div class="pure-form pure-flex-column-norm">
              <h3>Your crawl:</h3>
              <!-- Stores pub crawl with the given name -->
              <input type="text" v-model="crawlname" placeholder="Name this Crawl" v-on:keypress.enter="createCrawl">
              <button type="submit" class="pure-button" v-on:click="createCrawl">Submit</button>
            </div>
            <div class="pure-menu custom-restricted-width">
              <h6>click to remove</h6>
              <ul class="pure-menu-list">
                <div v-for="(selectedpub, i) in selectedpubs">
                  <!-- Clicking on pub card will remove it from this list and move it back to the list of nearby pubs -->
                  <li @click="pubDeselected(selectedpub, i)" class="pure-menu-item pure-flex-container pure-flex-column">
                    <div v-html="selectedpub.name"></div>
                    <div v-html="selectedpub.location.address1"></div>
                    <div>
                      <span v-html="selectedpub.location.city"></span>, <span v-html="selectedpub.location.state"></span> <span v-html="selectedpub.location.zip_code"></span>
                    </div>
                    <div v-bind:style="{ fontSize: .7 + 'em' }" class="pure-flex-row">
                      <div>[[selectedpub.newdistance]] [[selectedpub.unit]]</div>
                      <div>
                        <i class="fa fa-star" v-for="i in selectedpub.stars"></i><i class="fa fa-star-half" v-if="selectedpub.halfstar > 0"></i><span> ([[selectedpub.review_count]])</span>
                      </div>
                    </div>
                  </li>
                  <i class="fa fa-long-arrow-down fa-xs" v-if="i != selectedpubs.length - 1"></i>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          address: '',
          pubresults: [],
          origin: [],
          locations: [],
          submitted: false,
          displaymap: false,
          selectedpubs: [],
          crawlname: '',
          currentlat: 0,
          currentlon: 0,
          distance: 0,
        },
        methods: {
          // axios call of nearby pubs for a given address
          submitAddress: function() {
            if (this.address) {
              axios({
                method: 'post',
                url: '{% url 'sakanyapp:findpub' %}',
                headers: {
                  'X-CSRFToken':
                  '{{csrf_token}}'
                },
                data: {
                  address: this.address
                }
              }).then(response => {
                this.submitted = true
                this.address = ''
                console.log(response.data.pubresults)
                this.pubresults=response.data.pubresults
                this.origin = response.data.origin
                // convert metric distance into miles and feet
                // if distance is over 1000 ft, it returns the value as miles
                for (pub of this.pubresults) {
                  if (pub.distance > 304) {
                    pub.newdistance = (pub.distance * 0.000621371).toFixed(2)
                    pub.unit = "mi"
                  } else {
                    pub.newdistance = (pub.distance * 3.28084).toFixed(0)
                    pub.unit = "ft"
                  }
                  // separates the rating as an integer for number of stars and a zero or nonzero value for half stars
                  pub.stars = pub.rating -(pub.rating % 1)
                  pub.halfstar = pub.rating % 1
                }
              })
            }
          },
          mapPoints: function() {
            // currently unused function, for future map development
            for (pub in this.pubresults) {
              this.locations.push([pub.name, pub.coordinates.latitude, pub.coordinates.longitude])
            }
          },
          pubSelected: function(pub, i) {
            // move pub to the bottom of the array of selected pubs
            this.selectedpubs.push(pub)
            // use this pub as the new current location
            this.currentlat = pub.coordinates.latitude
            this.currentlon = pub.coordinates.longitude
            // remove pub from the current array
            this.pubresults.splice(i, 1)
            // run function to recalculate distances of all pubs in array of nearby pubs relative to new current location
            for (pubs of this.pubresults) {
              this.distCalc(pubs, i)
            }
            // reorder pubs by new shortest distance
            this.pubresults.sort((a, b) => {
              return a.distance - b.distance
            })
            // calculate distance of selected pubs relative to the previous pub in the array, first pub's distance is listed as 0
            index = 0
            for (pubs of this.selectedpubs) {
              index++
              // for the first pub in the array, store its coordinates as the starting location
              if (index == 1) {
                this.currentlat = pubs.coordinates.latitude
                this.currentlon = pubs.coordinates.longitude
              }
              this.distCalc(pubs, i)
              // stores current pub's coordinates as the starting location, so on next iteration, the next pub's coordinates are calculated against the previous pub in the array
              this.currentlat = pubs.coordinates.latitude
              this.currentlon = pubs.coordinates.longitude
            }
            console.log(this.selectedpubs)
          },
          pubDeselected: function(pub, i) {
            // move pub back to the array of nearby pubs
            this.pubresults.push(pub)
            // remove pub from array of selected pubs
            this.selectedpubs.splice(i, 1)
            // executes if the array of selected pubs is not empty
            if (this.selectedpubs.length > 0) {
              // uses last pub in the array of selected pubs as the new starting location
              this.currentlat = this.selectedpubs[this.selectedpubs.length-1].coordinates.latitude
              this.currentlon = this.selectedpubs[this.selectedpubs.length-1]
              index = 0
              for (pubs of this.selectedpubs) {
                index++
                if (index == 1) {
                  this.currentlat = pubs.coordinates.latitude
                  this.currentlon = pubs.coordinates.longitude
                }
                this.distCalc(pubs, i)
                this.currentlat = pubs.coordinates.latitude
                this.currentlon = pubs.coordinates.longitude
              }
            } else {
              // if array of selected pubs is empty, uses the original coodinates submitted by the user as the current location
              this.currentlat = this.origin[0]
              this.currentlon = this.origin[1]
            }
            for (pubs of this.pubresults) {
              this.distCalc(pubs, i)
            }
            this.pubresults.sort((a, b) => {
              return a.distance - b.distance
            })
            console.log(this.selectedpubs)
          },
          distCalc: function(pub, i) {
            //radius of the earth
            rad = 6371e3
            pi = Math.PI
            // convert decimal values into radians
            lat1 = this.currentlat * pi / 180
            lat2 = pub.coordinates.latitude * pi / 180
            deltalat = (pub.coordinates.latitude - this.currentlat) * pi / 180
            deltalon = (pub.coordinates.longitude - this.currentlon) * pi / 180
            // use trigonometric formulas to calculate distance
            alpha = Math.sin(deltalat/2) * Math.sin(deltalat/2) + Math.cos(lat1) * Math.cos(lat2) * Math.sin(deltalon/2) * Math.sin(deltalon/2)
            charlie = 2 * Math.atan2(Math.sqrt(alpha), Math.sqrt(1-alpha))
            // store pub's distance in meters
            pub.distance = rad * charlie
            // convert pub's distance into miles or feet
            if (pub.distance > 304) {
              pub.newdistance = (pub.distance * 0.000621371).toFixed(2)
              pub.unit = "mi"
            } else {
              pub.newdistance = (pub.distance * 3.28084).toFixed(0)
              pub.unit = "ft"
            }
          },
          // creates new pub crawl and opens the user's profile page
          createCrawl: function() {
            if (this.selectedpubs && this.crawlname) {
              axios({
                method: 'post',
                url: '{% url 'sakanyapp:newcrawl' %}',
                headers: {
                  'X-CSRFToken':
                  '{{csrf_token}}'
                },
                data: {
                  pub_route: this.selectedpubs,
                  crawlname: this.crawlname
                }
              }).then(response => {
                window.location = "{% url 'sakanyapp:profile' %}"
              })
            }
          }
        }
      })
      console.log(app.locations)
    </script>
  </body>
</html>

sakanytaurus/sakanyapp/templates/sakanyapp/index_backup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- import Vue framework -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script type="text/javascript" src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!-- import Pure CSS framework -->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/sakanyapp/stylesheet.css">
    {% load static %}
    <title></title>
  </head>
  <body>
    <div id="app">
      <div class="header">
        <div class="home-menu pure-menu-horizontal pure-menu-fixed">
          <a class="pure-menu-heading" href=""><img src="{% static "sakanyapp/logo2.png" %}" alt="logo"></a><span class="pure-menu-heading"> A Pub Crawler</span>
        </div>
      </div>
      <div class="main">
        <div class="pure-form pure-flex">
          <input type="text" v-model="address" placeholder="Input an address" v-on:keypress.enter="submitAddress">
          <button type="submit" class="pure-button" v-on:click="submitAddress">Submit</button>
        </div>
        <div>
          [[ origin[0] ]]
        </div>
        <div>
          [[ origin[1] ]]
        </div>
        <div v-for="pub in pubresults">
          [[ pub.alias ]]
        </div>
        <div id="map" style="height: 60vh; width: 80vw;"></div>
      </div>
    </div>

    <script type="text/javascript">
      // var locations = [
      //   ['Bondi Beach', -33.890542, 151.274856, 4],
      //   ['Coogee Beach', -33.923036, 151.259052, 5],
      //   ['Cronulla Beach', -34.028249, 151.157507, 3],
      //   ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
      //   ['Maroubra Beach', -33.950198, 151.259302, 1]
      // ];
      var coordinates
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -33.92, lng: 151.25},
          zoom: 10,
        });
        var infowindow = new google.maps.InfoWindow();

        var marker, i;

        setTimeout(function(){
          for (i = 0; i < locations.length; i++) {
            createMarkers(i);
          }
        }, 200)
      }
      function createMarkers(i) {
        setTimeout(function() {
          marker = new google.maps.Marker({
            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
            title:locations[i][0],
            map: map,
            animation: google.maps.Animation.DROP
          });
          google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
              infowindow.setContent(locations[i][0]);
              infowindow.open(map, marker);
            }
          })(marker, i));
        }, 200*i);
      }

      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          address: '',
          pubresults: {},
          origin: [],
          locations: []
        },
        methods: {
          submitAddress: function() {
            if (this.address) {
              axios({
                method: 'post',
                url: '{% url 'sakanyapp:findpub' %}',
                headers: {
                  'X-CSRFToken':
                  '{{csrf_token}}'
                },
                data: {
                  address: this.address
                }
              }).then(response => {
                this.address = ''
                console.log(response.data.pubresults)
                this.pubresults=response.data.pubresults
                this.origin = response.data.origin
                mapPoints()
              })
            }
          },
          mapPoints: function() {
            for (pub in this.pubresults) {
              this.locations.push([pub.name, pub.coordinates.latitude, pub.coordinates.longitude])
            }
          }
        }
      })
      console.log(app.locations)
    </script>
    <script src="http://maps.google.com/maps/api/js?key={{mapapi}}&callback=initMap" async defer></script>
  </body>
</html>

sakanytaurus/sakanyapp/templates/sakanyapp/profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- import Vue framework -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script type="text/javascript" src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!-- import Pure CSS framework -->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" SameSite=None>
    <link rel="stylesheet" href="/static/sakanyapp/stylesheet.css">
    {% load static %}
    <title></title>
  </head>
  <body>
    <div id="app">
      <!-- creates title header with profile and logout buttons -->
      <div class="header">
        <div class="home-menu pure-menu-horizontal pure-menu-fixed">
            <div class="">
              <a class="pure-menu-heading" href="/"><img src="{% static "sakanyapp/logo2.png" %}" alt="logo"></a>
              <div class="pure-menu-heading">A Pub Crawler</div>
            </div>
            <div class="pure-menu-buttons">
                <a class="pure-button" href="profile">PROFILE</a>
                <a class="pure-button" href="{% url 'sakanyapp:logout' %}">LOGOUT</a>
            </div>
        </div>
      </div>
      <div class="main">
        <h3>Click on a pub to navigate</h3>
        <!-- Display pub routes -->
        <div v-for="route in routes">
          <h2><div class="pure-flex-row-center">
            <div></div>
            <div v-html="route.name"></div>
            <a v-bind:href="'/delete/' + route.id"><i class="fa fa-times-circle"></i></a>
          </h2>
          <div v-for="(step, index) in route.steps" class="pure-button-group" role="group">
            <!-- clicking on pub card opens compass page -->
            <button class="pure-button" @click="openCompass(step, index)">
              <div v-html="step.loc_name"></div>
              <div v-html="step.loc_address"></div>
              <div class="pure-flex-row">
              <div>[[step.newdistance]] [[step.unit]]</div>
                <div>
                  <i class="fa fa-star" v-for="i in step.stars"></i><i class="fa fa-star-half" v-if="step.halfstar > 0"></i><span> ([[step.review_count]])</span>
                </div>
              </div>
            </button><br>
            <i class="fa fa-long-arrow-down" v-if="index != route.steps.length - 1"></i>
          </div>
        </div>
        <br>
      </div>
    </div>
    <script type="text/javascript">
      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          routes: []
        },
        methods: {
          getRoutes: function() {
            axios({
              method: 'get',
              url: '{% url 'sakanyapp:routes' %}'
            }).then(response => {
              this.routes = response.data.routes
              console.log(this.routes)
            })
          },
          // send currently selected pub's location to compass page
          openCompass: function(pub, index) {
              window.location = "{% url 'sakanyapp:compass' %}?publat="+pub.loc_lat+"&publon="+pub.loc_lon
          }
        },
        created: function(){
          this.getRoutes()
        }
      })
    </script>
  </body>
</html>